[package]
name = "hon-zoom-hack"
version = "0.1.0"
authors = ["Reinis Muiznieks <muiznieks.reinis@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
goblin = "0.0.22"
proc-maps = "0.1.5"
nix = "0.13.0"
byteorder = "1.3.1"